config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :photos, only: [ :new, :create, :show, :index ] do
    collection do
      post :image_search
    end
  end

  root to: "photos#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :file
  has_neighbors :embedding, dimensions: 512

  after_create :calculate_embedding

  def similar
    nearest_neighbors(:embedding, distance: :cosine)
  end

  def self.by_description(description)
    embedding = $text_embedding.call(description)
    nearest_neighbors(:embedding, embedding, distance: :cosine)
  end

  def self.by_image(image)
    embedding = $image_embedding.call(image.path)
    nearest_neighbors(:embedding, embedding, distance: :cosine)
  end

  def file_path
    ActiveStorage::Blob.service.send(:path_for, file.key)
  end

  private

  def calculate_embedding
    PhotoEmbedJob.perform_later(self)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to @photo, notice: "Photo was successfully uploaded."
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def index
    if params[:text_search].present?
      @photos = Photo.by_description(params[:text_search])
    else
      @photos = Photo.all
    end
  end

  def image_search
    if params[:image_search].present?
      @photos = Photo.by_image(params[:image_search])
    else
      @photos = Photo.all
    end
    render :index
  end


  private

  def photo_params
    params.require(:photo).permit(:file)
  end
end

app/views/photos/index.html.erb
<h1 class="mb-4">Photos</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_with url: photos_path, method: :get, local: true, class: "mb-4", id: "text-search-form" do %>
      <div class="input-group">
        <%= text_field_tag :text_search, params[:text_search], class: "form-control", placeholder: "A white cat with yellow eyes" %>
        <div class="input-group-append">
          <button type="button" class="btn btn-primary" onclick="submitTextSearchForm()">Search by query</button>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= form_with url: image_search_photos_path, method: :post, class: "mb-4", id: "image-search-form", html: { multipart: true }, data: { turbo: false } do %>
      <div class="input-group">
        <%= file_field_tag :image_search, class: "form-control" %>
        <div class="input-group-append">
          <input type="submit" class="btn btn-primary" value="Search by image">
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <% @photos.limit(9).select{ |photo| photo.file.present? }.each do |photo| %>
    <div class="col-md-4 mb-4">
      <%= link_to photo_path(photo) do %>
        <div class="card">
          <%= image_tag photo.file, class: "card-img-top img-fluid", style: "max-width: 100%; height: auto;" %>
          <div class="card-body">
            <% if photo.try(:neighbor_distance) %>
            Distance: <small class="text-muted"><%= photo.neighbor_distance.round(2) %></small>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Upload New Photo', new_photo_path, class: "btn btn-secondary" %>

<script>
    function submitTextSearchForm() {
        const form = document.getElementById('text-search-form');
        const searchInput = form.querySelector('input[name="text_search"]');
        const searchValue = searchInput.value;
        const url = new URL(form.action);
        url.searchParams.set('text_search', searchValue);
        window.location.href = url.toString();
    }
</script>

app/views/photos/new.html.erb
<h1 class="mb-4">Upload a new photo</h1>

<%= form_with model: @photo, local: true, class: "form" do |form| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
        <% @photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :file, class: "form-label" %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Upload", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/photos/show.html.erb
<h1 class="mb-4">Photo</h1>

<p>
  <%= image_tag @photo.file, style: "max-width: 500px; height: auto;", class: "img-fluid" %>
</p>

<h2>Similar photos</h2>
<div class="row">
  <% @photo.similar.limit(9).select{ |photo| photo.file.present? }.each do |photo| %>
    <div class="col-md-4 mb-4">
      <%= link_to photo_path(photo) do %>
        <div class="card">
          <%= image_tag photo.file, class: "card-img-top img-fluid", style: "max-width: 100%; height: auto;" %>
          <div class="card-body">
            <% if photo.try(:neighbor_distance) %>
              Distance: <small class="text-muted"><%= photo.neighbor_distance.round(2) %></small>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', photos_path, class: "btn btn-secondary" %>